### PR TITLE
Feature/ start delay

### PR DESCRIPTION
**Pull request by kikoseijo**
What about the possibility to add a little delay to the animation to run?

### CODE REVIEW

**Comment by elicwhite** [comment]
Could you just delay when you set isLoaded?

**Comment by kikoseijo** [comment]
You mean that I could using a ref, load the mask loader without the `isLoaded` and then set it up after the desired delay?

Didn't thought about it, yes, but you don't have to accept the PR, its a single class and I have customised per my needs, just thought could be handy.

**Comment by elicwhite** [comment]
I don’t think you need a ref, just set a timer that sets state in a parent component which passes the new value for the isLoaded prop.

**Comment by elicwhite** [comment]
You can see an example of what I mean by seeing how I use this loader in one of my projects: https://github.com/TheSavior/trakt-watchlist/blob/master/App.js#L17

**Pull request closed without merging**
